version: "3.9"

services:
  auth:
    container_name: "authentication"
    image: "authentication"
    build:
      context: .\Authentication\
      dockerfile: authentication.dockerfile
    ports:
      - "5002:5000"
    depends_on:
      - "postgres"
    networks:
      - challenge-network
    environment:
      - ASPNETCORE_URLS=http://+:5000

  web:
    container_name: "challenge-ef"
    image: "challenge_ef"
    build:
      context: .\Challenge_EF\
      dockerfile: challenge_ef.dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - "postgres"
      - "auth"
    networks:
      - challenge-network
    environment:
      - DATABASE="Host=postgres;Database=postgres;Username=postgres;Password=password"
      - ASPNETCORE_URLS=http://+:5000
      - IDENTITY_SERVER="http://auth"
      - FRONTEND_PATH="http://+:4200"

  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - challenge-network

networks:
  aspnetcoreapp-network:
    driver: bridge
